services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"              
    networks:
      - finance-project-network
    depends_on:
      - db
      - redis

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: FinanceProject
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - finance-project-network

  redis:
    image: redis:alpine
    networks:
      - finance-project-network
    volumes:
      - redisdata:/data 

networks:
  finance-project-network:

volumes:
  pgdata:
  redisdata: